# Site title and description
title: "Marcus Vos - Data Analyst Portfolio"
description: "Showcasing data analysis, visualization, and machine learning projects by Marcus Vos."

# URL configuration
baseurl: "/Projects" # The subpath of your site
url: "https://marcus8009.github.io" # Your GitHub Pages URL including subpath

# Theme for GitHub Pages
theme: jekyll-theme-cayman # You can choose any theme that fits your style

# Navigation configuration (links shown in the header)
nav:
  - title: "Home"
    url: "/Projects/"
  - title: "Machine Learning"
    url: "/Projects/ml.md"
  - title: "Data Cleaning"
    url: "/Projects/cleaning.md"
  - title: "Power BI Visualization"
    url: "/Projects/powerbi.md"
  - title: "Tableau Visualization"
    url: "/Projects/tableau.md"

# Markdown configuration
markdown: kramdown
kramdown:
  input: GFM

# Exclude files that shouldn't be processed
exclude:
  - README.md

# Include folder for assets (images, etc.)
include:
  - assets

# Permalinks configuration (custom URL structure for posts and pages)
permalinks:
  pretty: true
