title: "Marcus Vos Portfolio"
description: "A showcase of data cleaning, data visualization, and machine learning projects by Marcus Vos."
baseurl: "/Projects" # The subpath of your site
url: "https://marcus8009.github.io" # Your GitHub Pages URL

# Theme for GitHub Pages (you can change this to any Jekyll theme)
theme: minima

# Navigation links (these will appear in the header)
nav:
  - title: "Home"
    url: "/Projects/"
  - title: "Machine Learning"
    url: "/Projects/ml.md"
  - title: "Data Cleaning"
    url: "/Projects/cleaning.md"
  - title: "Power BI Visualization"
    url: "/Projects/powerbi.md"
  - title: "Tableau Visualization"
    url: "/Projects/tableau.md"

# Markdown configuration
markdown: kramdown
kramdown:
  input: GFM

# Exclude files that shouldn't be processed (like README)
exclude:
  - README.md

# Include folder for assets
include:
  - assets
