title: "Marcus Vos Portfolio"
theme: jekyll-theme-slate

# Navigation tabs
nav:
  - Machine Learning: ml.md
  - Data Cleaning: cleaning.md
  - Power BI Visualization: powerbi.md
  - Tableau Visualization: tableau.md
